---
# tasks file for mapr-nodemanager
- name: install mapr-nodemanager packages
  become: yes
  become_user: root
  yum: name='{{item}}' state=present
  with_items:
    - mapr-nodemanager

- name: find hadoop version
  shell: rpm -qa --queryformat '%{VERSION} %{RELEASE}' mapr-hadoop-core | awk '{ print substr($0,0,5) }'
  register: hadoop_version
  changed_when: false

- name: configure yarn.log-aggregation-enable
  become: yes
  become_user: root
  hadoop_properties: file=/opt/mapr/hadoop/hadoop-{{hadoop_version.stdout}}/etc/hadoop/yarn-site.xml name=yarn.log-aggregation-enable value=true
  notify: restart nodemanager
  when: configure_log_aggregation
