---
# handlers file for mapr-nodemanager

- name: restart nodemanager
  become: yes
  become_user: '{{mapr_admin_username}}'
  command: maprcli node services -action restart -name nodemanager -filter csvc==nodemanager
